openapi: 3.0.1
info:
  title: StudentProject API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Generated server url
paths:
  /api/v1/student:
    get:
      tags:
        - student-controller
      operationId: getStudents
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
    post:
      tags:
        - student-controller
      operationId: registerNewStudent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        '200':
          description: OK
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        dob:
          type: string
          format: date
        age:
          type: integer
          format: int32
