const advices = [
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    },
    {
        "id" : 2,
        "src" : "images/condus_ploaie.png",
        "title" : "Sfaturi pe timp de ploaie",
        "content" : "Reduceți viteza de deplasare în cazul unui carosabil umed.Viteza de deplasare nu trebuie să depășească 30km/h în localități și 50km/h în afara acestora atunci când vizibilitatea este redusă sub 100 de metri atunci când plouă torențial."
    },
    {
        "id" : 3,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi cand plecati in vacanta",
        "content" : "Vara este perioada in care majoritatea persoanelor pleaca in vacanta. Acest lucru se poate observa cel mai bine in trafic. In aceasta perioada, cuvantul „vacanta” devine sinonim cu aglomeratie, claxoane, ambuteiaje. Daca alegeti sa calatoriti cu masina, trebuie sa tineti cont de cateva sfaturi.Cea mai importanta regula cand sunteti la volan este sa nu va enervati. Fiti calmi! Condusul prin orase aglomerate poate fi un motiv de stres. Asadar, in cazul in care a existat o situatie neplacuta in trafic care v-a enervat, opriti masina sau gasiti metode de a va relaxa."
    },
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    },
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    },
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    },
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    },
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    },
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    },
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    },
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    },
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    },
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    },
    {
        "id" : 1,
        "src" : "images/drumInzapezit.jpg",
        "title" : "Sfaturi pe timp de ninsoare",
        "content" : "Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        Pregateste-ti masina pentru iarna<br>        Asigurati-va ca masina dumneavoastra are tot ce ii trebuie, ma refer in special la lichide, cum ar fi lichidul de frana si combustibilul. De preferat este ca atunci cand intentionati sa plecati la un drum lung sa aveti cel putin jumate combustibil in rezervor. Asigurati-va ca ati schimbat uleiul de motor cu cel indicat pentru iarna si ca toate celelalte fluide de la motorul masinii au fost completate.<br>        "
    }
]